# Site settings
title: Florian Schmitt
description: Florian Schmitt
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://florianschmitt.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Florian Schmitt
user_description: Full Stack Software Entwickler aus Köln mit Erfahrung in der Umsetzung von Software-Entwicklungs-Projekten in modernen Webtechnologien.
user_title: Full Stack Software Entwickler
email: florian@florianschmitt.de
twitter_username: lorem_ipsum
github_username:  florianschmitt
gplus_username:  lorem_ipsum

# Google-analytics
# google-analytics:
#   id: ""

exclude: ['package.json', 'src' , 'node_modules']
include: ['_pages', '_data']
